sudo: false

language: c

addons:
    apt:
        sources:
        - llvm-toolchain-precise-3.5
        - ubuntu-toolchain-r-test
        packages:
        - clang
        - g++-4.8
        - gcc-4.8
        - libedit-dev
        - libgmp-dev
        - llvm-3.5-dev

cache:
    directories:
    - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip=1 -C ~/.local/bin '*/stack'

install:
- travis_wait stack $ARGS --no-terminal --skip-ghc-check setup
- travis_wait stack $ARGS --no-terminal --skip-ghc-check test --only-snapshot

script:
- stack $ARGS --no-terminal --skip-ghc-check test
