packages:
- '.'
- location:
    git:    https://github.com/qux-lang/language-qux
    commit: 3c137ac929dbdb4c8b80ff413968bdfd1e51ec08

resolver:   lts-3.10
extra-deps: ['language-qux-0.2.0.0', 'llvm-general-3.4.5.4', 'llvm-general-pure-3.4.5.4']

