packages:
- '.'
- location:
    git:    https://github.com/qux-lang/language-qux
    commit: 7bdc0c89e4bde049eaab52d0a94d451972fa6f65

resolver: lts-3.10

extra-deps:
- language-qux-0.2.0.0
- llvm-general-3.4.5.4
- llvm-general-pure-3.4.5.4

