packages:
- '.'
- location:
    git: git@github.com:qux-lang/language-qux
    commit: refs/remotes/origin/release/0.1
    extra-dep: true
ghc-options:
    'qux': -Wall -Werror -fno-warn-name-shadowing

resolver: lts-3.4
extra-deps: ['llvm-general-3.4.5.4', 'llvm-general-pure-3.4.5.4']

