resolver: lts-9.0
ghc-options:
    qux: -Werror -Wall -fno-warn-name-shadowing

packages:
- '.'
- location:
    git:    https://github.com/hjwylde/language-qux
    commit: fcd5a4be32dc0140c4828a7e018082abf423a959
  extra-dep: true
